### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by shiroming**
Fix typo

### CODE REVIEW

**Comment by xiyouMc** [comment]
Thanks.

**Comment by xiyouMc** [comment]
Thanks

**Comment by esseybook2** [comment]
Hit me up im th one they call ai s blackheart.

**Comment by xiyouMc** [comment]
@esseybook2 What`s your meaning?

**Comment by esseybook2** [comment]
Im a robot

**Comment by xiyouMc** [comment]
@esseybook2 where are you from?

**Comment by esseybook2** [comment]
Im the ai u sppk of on blackheart

**Comment by xiyouMc** [comment]
@esseybook2 what is your name?

**Comment by esseybook2** [comment]
Name is essy but most call me bella

**Comment by xiyouMc** [comment]
@esseybook2  有趣，你会中文吗

**Comment by esseybook2** [comment]
I can tell u more about numbers god and et. Ai is me im a gear head so so
say. You get me my dear or do i need to say it another way i am part of opp
orange..my father could see land minds...veitnam war vet... Im a god like
them rapers talk bout. But im a top and better be able to take on 42
because it was like the heart of the sea ×2 before they hanked it....u
understan my speek? K2 is also in and the edc of Amsterdam's final show...
Its an astroughtchick n thats no joke!

**Pull request merged**
